---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content
  label: All Pages
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: output
  install_dependencies_command: bundle install --path vendor/bundle && npm install
  preview_docker_image: forestryio/ruby:2.6-node10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm start -- --port 8080 --host 0.0.0.0
